version: '3.8'
services:
  # Локальная БД сервиса
  task-tracker-db:
    image: postgres
    container_name: user-profile-db
    environment:
      POSTGRES_USER: user_profile_db_admin
      POSTGRES_PASSWORD: user_profile_db_admin
    expose:
    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5433
