spring:
  application:
    name: user-profile-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_profile
    username: user_profile_db_client
    password: user_profile_db_client
  liquibase:
    enabled: true
    change-log: classpath:db.scripts/changelog-master.xml
    url: jdbc:postgresql://localhost:5433/user_profile
    user: user_profile_db_admin
    password: user_profile_db_admin
    liquibase-schema: "liquibase"
    default-schema: "user_profile"
  jpa:
    database: POSTGRESQL
    show-sql: true

server:
  port: 8085
